# Generated by Django 2.2.1 on 2019-05-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaZhong',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_reviewcount', models.IntegerField(max_length=200)),
                ('shop_avgpricetitle', models.IntegerField(max_length=200)),
                ('shop_effect', models.FloatField()),
                ('shop_service', models.FloatField()),
                ('shop_surroundings', models.FloatField()),
                ('shop_address', models.CharField(max_length=200)),
                ('shop_telephonenumber', models.CharField(max_length=200)),
                ('shop_businesshours', models.CharField(max_length=200)),
                ('shop_url', models.CharField(max_length=200)),
                ('shop_star', models.CharField(max_length=200)),
            ],
        ),
    ]
