# Generated by Django 2.2.1 on 2019-05-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dazhong',
            name='shop_name',
            field=models.CharField(max_length=100),
        ),
    ]
